spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/growstory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    username: smiledk
#    password: 1112
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${G_CLIENT_ID}
            client-secret: ${G_CLIENT_SECRET}
            redirect-uri: http://localhost:8888/login/oauth2/code/google
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587 # SMTP에서 보안성을 추가한 SMTPS의 서버 포트 = 587
    username: dndbskfkek@gmail.com
    password: ixeh cmvj ojlk sojn
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      # SMTP(Simple Mail Transfer Protocol)
      # starttls는 목적지 서버에서 TLS(Transport Layer Security)를 지원하지 않더라도 587포트를 사용가능하게 한다

jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: trace

# swagger
springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

mail:
  admin:
    address: ${ADMIN_EMAIL}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: growstory/image/profile
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8888
